reviewPage/urls.py
from django.urls import path, re_path
from . import views

app_name = 'reviewPage'

urlpatterns = [
    path('<str:produk>/', views.ReviewView.get, name='productReview'),
    path('<str:produk>/add', views.review, name='addReview'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('advice/', include('advice.urls')),
    path('products/', include('products.urls')),
    path('review/', include('reviewPage.urls')),
]

reviewPage/models.py
from django.db import models

# Create your models here.

class ReviewModel(models.Model):
    produknya = models.CharField(max_length = 20)
    namaReview = models.CharField(max_length = 100)
    isiReview = models.TextField(max_length = 400)

    def __str__(self):
        return self.namaReview

reviewPage/forms.py
from django import forms
from .models import ReviewModel
from crispy_forms.helper import FormHelper

class ReviewForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False

    class Meta:
        model = ReviewModel
        fields = { 'namaReview' , 'isiReview'}

reviewPage/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .forms import ReviewForm
from .models import ReviewModel

class ReviewView(TemplateView):
    template_name = 'reviewPage.html'


    def get(request, produk):
        temp = produk
        form = ReviewForm()
        reviews = ReviewModel.objects.filter(produknya=produk)
        args = {
            'reviews' : reviews,
            'produk' : produk
        }

        return render(request, 'reviewPage.html', args)

def review(request, produk):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.produknya = produk
            obj.save()
            return redirect('reviewPage:productReview', produk)
    else:
        form = ReviewForm()
    return render(request, 'reviewForm.html', {'form':form})

reviewPage/templates/reviewForm.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}
    <div class="container">
        <div class="mr-auto "style="
            margin-top : 100px;
            font-family: Roboto;
            font-style: normal;
            font-size: 3em;
            color: #8D6011;">
            <div class="row mr-auto" >
                <div class="col">
                    <p class="font-weight-bolder">Review</p>
                </div>
            </div>
            <div class="row mr-auto">
                <div class="col">
                    <p class="font-weight-lighter">this product</p>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="jumbotron" style="background-color: #4A5E26;
            display: flex;
            flex-direction: column;
            width: 65vw;">
                    <form action='' method ="POST">
                            {% csrf_token %}
                            <div class="row mr-auto">
                                <div class="col">
                                    <label style="font-family: Roboto;
                                    font-style: normal;
                                    font-weight: normal;
                                    font-size: 24px;
                                    line-height: 28px;
                                    
                                    color: #F4F5F0;">Name:</label>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        {{ form.namaReview|as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                            <div class="row mr-auto">
                                <div class="col">
                                    <label style="font-family: Roboto;
                                    font-style: normal;
                                    font-weight: normal;
                                    font-size: 24px;
                                    line-height: 28px;
                                    
                                    color: #F4F5F0;">Suggestion:</label>
                                </div>
                                <div class="col">
                                    <div class="form-group input-md">
                                        {{ form.isiReview|as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                            
                            
                            <br>
                            <input type="submit" name="submit" value="Submit" class="btn" style="background: #FADC44;">
                        
                        </form>
                
            </div>


                        

        </div>
        
    </div>
{% endblock content %}

reviewPage/templates/reviewPage.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="row mr-auto" style="
    font-family: Roboto;
    font-style: normal;
    font-weight: 900;
    color: #8D6011;">
        <div class="col-sm">
            <h1 style="font-weight: bold;
            font-size: 3em;">Review</h1>
        </div>
        <div class="col">
            <h1 style="font-size: 3em; margin-bottom: 40px;">about</h1>
        </div>
    </div>
    <div class="row">
        <div class="card">
            <div class="row no-gutters">
                <div class="col-md-4">
                <img src="..." class="card-img" alt="insert image here">
                </div>
                <div class="col-md-8">
                    <div class="card-body bg-success text-white">
                        <h5 class="card-title">ERHA</h5>
                        <p class="card-text">Acne Spot Gel</p>
                        <p class="card-text">Acne Care Lab Acne Spot Gel merupakan rangkaian produk yang diformulasikan untuk mengurangi peradangan, mempercepat penyembuhan dan mencegah hiperpigmentasi pada Spot Jerawat Aktif. 
                            Dengan gel bening sehingga dapat dapat digunakan untuk day time, karena tidakmeninggalkan bekas di kulit.</p>
                        <p class="card-text">Cara Penggunaan:</p>
                        <p class="card-text">Gunakan pada jerawat serta area sekitarnya. Biarkan mengering.</p>
                        <p class="card-text">Komposisi:</p>
                        <p class="card-text">Mengandung Sulfur, BHA dan Niacinamide untuk membantu mengatasi, mengeringkan jerawat aktif, serta mencegah timbulnya
                                noda hitam pasca jerawat</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if reviews %}
        {% for s in reviews %}
            <div class="row mr-auto ">
                <h1 style="
                font-family: Roboto;
                font-style: normal;
                font-weight: 500;
                font-size: 18px;
                line-height: 21px;
                
                color: #8D6011;
                
                ">{{ s.namaReview }}</h1>
            </div>
            <div class="row mr-auto">
                <h1 style="
                font-family: Roboto;
                font-style: normal;
                font-weight: 300;
                font-size: 14px;
                line-height: 16px;
                
                color: #000000;">{{ s.isiReview }}</h1>
            </div>
        {% endfor %}
    {% else %}
        <div class="row mr-auto">
            <h1 style = "font-family: Roboto;
            font-style: normal;
            font-weight: 300;
            font-size: 1em;
            
            color: #8D6011;">Be the first to review this product!</h1>
        </div>
    {% endif %}
            <div class="row mr-auto">
                <a href="{% url 'reviewPage:addReview' produk %}" style="font-family: Roboto;
                font-style: normal;
                font-weight: 500;
                font-size: 1em;
                
                color: #000000;">
                    add review
                </a>
            </div>
    
    
</div>


{% endblock content %}