homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('summary/', views.summary, name = 'summary'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('hair/', views.hair, name='hair'),
    path('dandruff/', views.dandruff, name='dandruff'),
    path('hairLoss/', views.hairLoss, name='hairLoss'),
    path('dryHair/', views.dryHair, name='dryHair'),
    path('face/', views.face, name='face'),
    path('jerawat/', views.jerawat, name='jerawat'),
    path('berminyak/', views.berminyak, name='berminyak'),
    path('keringFace/', views.keringFace, name='keringFace'),
    path('normalFace/', views.normalFace, name='normalFace'),
    path('skin/', views.skin, name='skin'),
    path('normalSkin/', views.normalSkin, name='normalSkin'),
    path('drySkin/', views.drySkin, name='drySkin'),
    path('sensitifSkin/', views.sensitifSkin, name='sensitifSkin'),
]

reviewPage/urls.py
from django.urls import path, re_path
from . import views

app_name = 'reviewPage'

urlpatterns = [
    path('<str:produk>/', views.ReviewView.get, name='productReview'),
    path('<str:produk>/add', views.review, name='addReview'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('advice/', include('advice.urls')),
    path('products/', include('products.urls')),
    path('review/', include('reviewPage.urls')),
]

products/models.py
from django.db import models

hairCategory = {
    ('DANDRUFF', 'DANDRUFF'),
    ('DRY HAIR', 'DRY HAIR'),
    ('HAIR LOSS', 'HAIR LOSS')
}

faceCategory = {
    ('JERAWAT', 'JERAWAT'),
    ('BERMINYAK', 'BERMINYAK'),
    ('KERING', 'KERING'),
    ('NORMAL', 'NORMAL'),
}

skinCategory = {
    ('NORMAL', 'NORMAL'),
    ('KERING', 'KERING'),
    ('SENSITIF', 'SENSITIF'),
}
# Create your models here.
class hairCategory(models.Model):
    nama = models.CharField(max_length=20)
    hairCategory = models.CharField(max_length=20, choices=hairCategory)

    def __str__(self):
        return self.hairCategory

class faceCategory(models.Model):
    nama = models.CharField(max_length=20)
    faceCategory = models.CharField(max_length=20, choices=faceCategory)

    def __str__(self):
        return self.faceCategory

class skinCategory(models.Model):
    nama = models.CharField(max_length=20)
    skinCategory = models.CharField(max_length=20, choices=skinCategory)

    def __str__(self):
        return self.skinCategory

products/forms.py
from django import forms
from .models import hairCategory, faceCategory, skinCategory

class hairCategoryForm(forms.ModelForm):
    class Meta:
        model = hairCategory
        fields = {'nama','hairCategory'}
        widgets = {'nama' : forms.TextInput(
            attrs = {
                'class':'form-control',
            }
        ),
                'hairCategory': forms.Select(
                    attrs = {
                        'class': 'form-control',
                    }
                )}

class faceCategoryForm(forms.ModelForm):
    class Meta:
        model = faceCategory
        fields = {'nama','faceCategory'}
        widgets = {'nama' : forms.TextInput(
            attrs = {
                'class':'form-control',
            }
        ),
            'faceCategory': forms.Select(
                    attrs = {
                        'class': 'form-control',
                    }
                )}

class skinCategoryForm(forms.ModelForm):
    class Meta:
        model = skinCategory
        fields = {'nama','skinCategory'}
        widgets = {'nama' : forms.TextInput(
            attrs = {
                'class':'form-control',
            }
        ),
        'skinCategory': forms.Select(
                    attrs = {
                        'class': 'form-control',
                    }
                )}

products/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from homepage.models import Person
from .models import hairCategory, faceCategory, skinCategory
from .forms import hairCategoryForm, faceCategoryForm, skinCategoryForm

# Create your views here.
def hair(request):
    hair = hairCategoryForm(request.POST or None)
    if request.method == 'POST':
        if hair.is_valid():
            nama = request.POST['nama']
            if Person.objects.filter(name = nama).exists():
                obj = hair.save()
                if obj.hairCategory == 'DANDRUFF':
                    return redirect('products:dandruff')
                elif obj.hairCategory == 'HAIR LOSS':
                    return redirect('products:hairLoss')
                elif obj.hairCategory == 'DRY HAIR':
                    return redirect('products:dryHair')
            else:
                argument = {
                    'hairCategory': hair,
                    'gagal' : True
                }
                return render(request, 'hair.html', argument)
    
    argument = {
        'hairCategory': hair,
        'gagal' : False
    }
    return render(request, 'hair.html', argument)

def dandruff(request):
    return render(request,'dandruff.html')

def hairLoss(request):
    return render(request,'hairLoss.html')

def dryHair(request):
    return render(request,'dryHair.html')

def face(request):
    face = faceCategoryForm(request.POST or None)
    if request.method == 'POST':
        if face.is_valid():
            nama = request.POST['nama']
            if Person.objects.filter(name = nama).exists():
                obj = face.save()
                if obj.faceCategory == 'JERAWAT':
                    return redirect('products:jerawat')
                elif obj.faceCategory == 'BERMINYAK':
                    return redirect('products:berminyak')
                elif obj.faceCategory == 'KERING':
                    return redirect('products:keringFace')
                elif obj.faceCategory == 'NORMAL':
                    return redirect('products:normalFace')
            else:
                argument = {
                    'faceCategory': face,
                    'gagal' : True
                }
            return render(request, 'face.html', argument)

    argument = {
        'faceCategory': face,
        'gagal' : False
    }
    return render(request, 'face.html', argument)

def jerawat(request):
    return render(request,'jerawat.html')

def berminyak(request):
    return render(request,'berminyak.html')

def keringFace(request):
    return render(request,'keringFace.html')

def normalFace(request):
    return render(request,'normalFace.html')

def skin(request):
    skin = skinCategoryForm(request.POST or None)
    if request.method == 'POST':
        if skin.is_valid():
            nama = request.POST['nama']
            if Person.objects.filter(name = nama).exists():
                obj = skin.save()
                if obj.skinCategory == 'NORMAL':
                    return redirect('products:normalSkin')
                elif obj.skinCategory == 'KERING':
                    return redirect('products:drySkin')
                elif obj.skinCategory == 'SENSITIF':
                    return redirect('products:sensitifSkin')
                return redirect('products:skin')
            else:
                argument = {
                    'skinCategory': face,
                    'gagal' : True
                }
            return render(request, 'skin.html', argument)

    argument = {
        'skinCategory': skin,
        'gagal': False
    }
    return render(request, 'skin.html', argument)

def normalSkin(request):
    return render(request,'normalSkin.html')

def drySkin(request):
    return render(request,'drySkin.html')

def sensitifSkin(request):
    return render(request,'sensitifSkin.html')

products/templates/base.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <title>BODYOLOGY</title>
        <meta charset="UTF-8">
        <meta name=”viewport” content=”width=device-width, initial-scale=1″>
        <!-- <link rel="icon" type="img/png" href="https://files.catbox.moe/qoyk7z.png"> -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
        {% block customhead %}
        {% endblock customhead %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'homepage:home' %}">Bodyology</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0"></ul>
              <form class="form-inline my-2 my-lg-0">
                    <a class="nav-link" href="{% url 'homepage:home' %}">HOME</a>
                    <a class="nav-link" href="{% url 'products:hair' %}">HAIR</a>
                    <a class="nav-link" href="{% url 'products:face' %}">FACE</a>
                    <a class="nav-link" href="{% url 'products:skin' %}">SKIN</a>
                    <a class="nav-link" href="{% url 'homepage:summary' %}">SUMMARY</a>
                    <a class="nav-link" href="#">ADVICE</a>
              </form>
            </div>
          </nav>
          {% block content %}
          {% endblock content %}
        <!-- JavaScript -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/esm/popper-utils.js"></script>
        <script src="{% static 'bootstrap.bundle.min.js' %}"></script> 
    </body>
</html>
    

products/templates/berminyak.html
{% extends "base.html" %}
{% load static %}
{% block customhead %}
<link rel="stylesheet" type="text/css" href="{% static 'styleProduct.css' %}">
{% endblock customhead %}
{% block content %}
    <!-- face category -->
    <div id="faceCategory">
            <div class="container">
                <div class="row">
                <div id="category" class="col">
                    <h1>Hello, there^^</h1>
                    <form method="POST">
                        <div class="form-group">
                            <p>What is your face's skin type?</p>
                            <h3>Berminyak</h3>
                        </div>
                    </form>
                    </div>
                    <div class="col">
                    </div>
                </div>
            </div>
        </div>
        <!-- face products recommendation -->
        <div id="faceCategory">
            <h1 class="title" style="padding-top: 100px; text-align: center; justify-content: center;">Oily Skin Face Product</h1>
            <div class="container">
                <div class="row">
                    <!-- produk1 -->
                    <div class="col">
                      <div class="box-2">
                          <div class="row" style="justify-content: center;">
                              <img id="foto-produk" alt="OilyFace" src="https://files.catbox.moe/9eaj0u.jpg" width="200" height="auto">
                          </div>
                          <div class="row">
                              <p class="title description" style="font-weight: bold; font-size: 25px;">ELSHESKIN</p></br>
                              <div class="row">
                                    <p class="description" style="font-size: 17px;">Oily Cleanser Wash</p></br>
                                    <p class="description" style="font-size: 15px;">
                                        Pembersih wajah untuk membersihkan kotoran/debu yang menempel akibat wajah berminyak dan 
                                        mengurangi minyak berlebih di wajah. Kulit wajah menjadi lebih bersih, segar, mengurangi minyak berlebih.</p></br>
                            </div>
                          </div>
                          <div class="row">
                            <a href = "{% url 'reviewPage:productReview' 'ELSEHESKIN' %}" class="link">Review</a>
                            </div>
                          <div class="row">
                              <a href="https://www.sociolla.com/skin-care/10478-oily-cleanser-wash.html#/size-100" class="link">Click here if you're interested to buy</a>
                          </div>
                      </div>
                    </div>
                    <!-- produk2 -->
                    <div class="col">
                        <div class="box-2">
                            <div class="row" style="justify-content: center;">
                                <img id="foto-produk" alt="OilyFace" src="https://files.catbox.moe/pi61fa.jpg" width="200" height="auto">
                            </div>
                            <div class="row">
                                <p class="description" style="font-weight: bold; font-size: 25px;">BIODERMA</p></br>
                                <div class="row">
                                    <p class="description" style="font-size: 17px;">Sebium H2O Galaxy</p></br>
                                    <p class="description" style="font-size: 15px;">
                                        Sebium H2O adalah cairan micellar penghapus sisa riasan yang pertama untuk kulit kombinasi 
                                        atau kulit berminyak yang menyerupai komposisi alami kulit agar dapat menghilangkan sisa riasan 
                                        secara sempurna tanpa merusak kulit yang paling sensitif sekalipun.</p></br>
                                </div>
                            </div>
                            <div class="row">
                                <a href = "{% url 'reviewPage:productReview' 'BIODERMA' %}" class="link">Review</a>
                                </div>
                            <div class="row">
                                <a href = "https://www.sociolla.com/skin-care/14349-sebium-h2o-99.html" class="link">Click here if you're interested to buy</a>
                            </div>
                        </div>
                    </div>
                    <!-- end -->
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}

products/templates/dandruff.html
{% extends "base.html" %}
{% load static %}
{% block customhead %}
<link rel="stylesheet" type="text/css" href="{% static 'styleProduct.css' %}">
{% endblock customhead %}
{% block content %}
    <!-- hair category -->
    <div id="hairCategory">
            <div class="container">
                <div class="row">
                <div id="category" class="col">
                    <h1>Hello, there^^</h1>
                    <form method="POST">
                        <div class="form-group">
                            <p>What is your hair problem?</p>
                            <h3>Dandruff</h3>
                        </div>
                    </form>
                    </div>
                    <div class="col">
                    </div>
                </div>
            </div>
        </div>
        <!-- hair products recommendation -->
        <div id="hairCategory">
            <h1 class="title" style="padding-top: 100px; text-align: center; justify-content: center;">Dandruff Product</h1>
            <div class="container">
                <div class="row">
                    <!-- produk1 -->
                    <div class="col">
                      <div class="box-2">
                          <div class="row" style="justify-content: center;">
                              <img id="foto-produk" alt="Dandruff" src="https://files.catbox.moe/n240to.png" width="200" height="auto">
                          </div>
                          <div class="row">
                              <p class="title description" style="font-weight: bold; font-size: 25px;">HEAD & SHOULDER</p></br>
                              <div class="row">
                                    <p class="description" style="font-size: 17px;">Supreme Smooth Shampoo</p></br>
                                    <p class="description" style="font-size: 15px;">
                                        Argan, dikenal sebagai bahan alami untuk melembabkan kulit dan rambut. 
                                        Formula yang membantu mengunci kelembaban, 
                                        memperbaiki rambut kusam sehingga sehingga rambut tampak 
                                        berkilau dan terasa lembut.</p></br>
                            </div>
                          </div>
                          <div class="row">
                            <a href = "{% url 'reviewPage:productReview' 'HEAD & SHOULDER' %}" class="link">Review</a>
                            </div>
                          <div class="row">
                              <a href="https://www.headandshoulders.co.id/id-id/belanja-produk/shampo/supreme-smooth-shampo-anti-ketombe" class="link">Click here if you're interested to buy</a>
                          </div>
                      </div>
                    </div>
                    <!-- produk2 -->
                    <div class="col">
                        <div class="box-2">
                            <div class="row" style="justify-content: center;">
                                <img id="foto-produk" alt="Dandruff" src="https://files.catbox.moe/ugwkco.png" width="200" height="auto">
                            </div>
                            <div class="row">
                                <p class="description" style="font-weight: bold; font-size: 25px;">RUDY HADISUWARNO</p></br>
                                <div class="row">
                                    <p class="description" style="font-size: 17px;">Anti Dandruff Serum</p></br>
                                    <p class="description" style="font-size: 15px;">
                                        Serum ini bekerja melalui Triple Active Care Treatment 
                                        yang membantu menghilangkan ketombe, kemerahan, dan iritasi ringan pada kulit kepala 
                                        serta membersihkan sekaligus menjaga kelembapan kulit kepala. </p></br>
                                </div>
                            </div>
                            <div class="row">
                                <a href = "{% url 'reviewPage:productReview' 'RUDY HADISUWARNO' %}" class="link">Review</a>
                            </div>
                            <div class="row">
                                <a href = "https://www.tokopedia.com/vavabeauty4ever/obat-anti-ketombe-rudy-hadisuwarno-anti-dandruff-serum" class="link">Click here if you're interested to buy</a>
                            </div>
                        </div>
                    </div>
                    <!-- end -->
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}

products/templates/dryHair.html
{% extends "base.html" %}
{% load static %}
{% block customhead %}
<link rel="stylesheet" type="text/css" href="{% static 'styleProduct.css' %}">
{% endblock customhead %}
{% block content %}
    <!-- hair category -->
    <div id="hairCategory">
            <div class="container">
                <div class="row">
                <div id="category" class="col">
                    <h1>Hello, there^^</h1>
                    <form method="POST">
                        <div class="form-group">
                            <p>What is your hair problem?</p>
                            <h3>Rambut Kering</h3>
                        </div>
                    </form>
                    </div>
                    <div class="col">
                    </div>
                </div>
            </div>
        </div>
        <!-- hair products recommendation -->
        <div id="hairCategory">
            <h1 class="title" style="padding-top: 100px; text-align: center; justify-content: center;">Dry Hair Product</h1>
            <div class="container">
                <div class="row">
                    <!-- produk1 -->
                    <div class="col">
                      <div class="box-2">
                          <div class="row" style="justify-content: center;">
                              <img id="foto-produk" alt="DryHair" src="https://files.catbox.moe/5o375z.jpg" width="200" height="auto">
                          </div>
                          <div class="row">
                              <p class="title description" style="font-weight: bold; font-size: 25px;">SUNSILK</p></br>
                              <div class="row">
                                    <p class="description" style="font-size: 17px;">Nourishing Soft & Smooth</p></br>
                                    <p class="description" style="font-size: 15px;">
                                        Dilengkapi dengan 5 natural oils yang ringan dan tidak lengket di rambut. Formulanya menutrisi ke dalam
                                        setiap helai rambut dan menciptakan lapisan yang mampu melindungi dan menutrisi rambut.</p></br>
                            </div>
                          </div>
                          <div class="row">
                            <a href = "{% url 'reviewPage:productReview' 'SUNSILK' %}" class="link">Review</a>
                            </div>
                          <div class="row">
                              <a href="https://www.bukalapak.com/p/perawatan-kecantikan/makeup/rambut/1kf8id4-jual-sunsilk-shampoo-soft-smooth-340ml-conditioner-black-shine-170ml?from=&product_owner=normal_seller" class="link">Click here if you're interested to buy</a>
                          </div>
                      </div>
                    </div>
                    <!-- produk2 -->
                    <div class="col">
                        <div class="box-2">
                            <div class="row" style="justify-content: center;">
                                <img id="foto-produk" alt="DryHair" src="https://files.catbox.moe/wxxjt3.jpg" width="200" height="auto">
                            </div>
                            <div class="row">
                                <p class="description" style="font-weight: bold; font-size: 25px;">L'OREAL PARIS</p></br>
                                <div class="row">
                                    <p class="description" style="font-size: 17px;">Smooth-Intense Anti-Frizz Shampoo</p></br>
                                    <p class="description" style="font-size: 15px;">
                                        Diperkaya dengan argan oil yang menjadikan rambut kusut tampak halus dan thermo-protect agent
                                        yang merawat dan melindungi rambut dari efek lembab seperti rambut kusut dan mengembang tidak beratur.</p></br>
                                </div>
                            </div>
                            <div class="row">
                                <a href = "{% url 'reviewPage:productReview' 'LOREAL PARIS' %}" class="link">Review</a>
                            </div>
                            <div class="row">
                                <a href = "https://shopee.co.id/L'Oreal-Paris-Smooth-Intense-Anti-Frizz-Shampo-i.8077122.2105908094" class="link">Click here if you're interested to buy</a>
                            </div>
                        </div>
                    </div>
                    <!-- end -->
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}

products/templates/drySkin.html
{% extends "base.html" %}
{% load static %}
{% block customhead %}
<link rel="stylesheet" type="text/css" href="{% static 'styleProduct.css' %}">
{% endblock customhead %}
{% block content %}
    <!-- skin category -->
    <div id="skinCategory">
            <div class="container">
                <div class="row">
                <div id="category" class="col">
                    <h1>Hello, there^^</h1>
                    <form method="POST">
                        <div class="form-group">
                            <p>What is your skin type?</p>
                            <h3>Kulit Kering</h3>
                        </div>
                    </form>
                    </div>
                    <div class="col">
                    </div>
                </div>
            </div>
        </div>
        <!-- skin products recommendation -->
        <div id="skinCategory">
            <h1 class="title" style="padding-top: 100px; text-align: center; justify-content: center;">Dry Skin Product</h1>
            <div class="container">
                <div class="row">
                    <!-- produk1 -->
                    <div class="col">
                      <div class="box-2">
                          <div class="row" style="justify-content: center;">
                              <img id="foto-produk" alt="dry-skin" src="https://files.catbox.moe/0rttdb.jpg" width="200" height="auto">
                          </div>
                          <div class="row">
                              <p class="title description" style="font-weight: bold; font-size: 25px;">MUSTIKA RATU</p></br>
                              <div class="row">
                                    <p class="description" style="font-size: 17px;">Mustika Ratu Hand & Body Lotion Zaitun</p>                                  </p></br>
                                    <p class="description" style="font-size: 15px;">
                                        Mustika Ratu Zaitun Hand and Body Lotion merupakan losion pelembab yang mudah menyerap pada kulit, 
                                        membantu menjaga kelembutan dan kelembaban kulit.</p></br>
                            </div>
                          </div>
                          <div class="row">
                                <a href = "{% url 'reviewPage:productReview' 'MUSTIKA RATU' %}" class="link">Review</a>
                            </div>
                          <div class="row">
                              <a href="https://shopee.co.id/Hand-and-body-lotion-zaitun-mustika-ratu-i.70376683.1357556860/similar?from=ads&gclid=CjwKCAjwxaXtBRBbEiwAPqPxcPd0Hq-rn-I8MFlcFzTFWUjrNaYA2tgiGsTG8aoVpVKStTaBcyOhshoC740QAvD_BwE" class="link">Click here if you're interested to buy</a>
                          </div>
                      </div>
                    </div>
                    <!-- produk2 -->
                    <div class="col">
                        <div class="box-2">
                            <div class="row" style="justify-content: center;">
                                <img id="foto-produk" alt="dry-skin" src="https://files.catbox.moe/lfbt6y.jpg" width="200" height="auto">
                            </div>
                            <div class="row">
                                <p class="description" style="font-weight: bold; font-size: 25px;">NIVEA</p></br>
                                <div class="row">
                                    <p class="description" style="font-size: 17px;">Nivea Intensive Moisture Lotion</p></br>
                                    <p class="description" style="font-size: 15px;">
                                        Nivea Body Lotion Intensive Moisture dilengkapi formula yang diperkaya dengan Grape Seed 
                                        & Avocado Oil untuk melembabkan kulit secara intensif dan merawat kulit. Formulanya dapat 
                                        mengembalikan dan melengkapi kelembaban yang hilang, meningkatkan lapisan alami pelindung 
                                        kulit, dan memberikan kelembaban selama 24 jam. Telah diuji secara dermatologis cocok untuk 
                                        kulit, tidak mengandung pewarna.</p></br>
                                </div>
                            </div>
                            <div class="row">
                                <a href = "{% url 'reviewPage:productReview' 'NIVEA LOTION' %}" class="link">Review</a>
                            </div>
                            <div class="row">
                                <a href = "https://shopee.co.id/Nivea-Body-Lotion-Intensive-Moisture-400ml-i.8500136.215326515" class="link">Click here if you're interested to buy</a>
                            </div>
                        </div>
                    </div>
                    <!-- end -->
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}

products/templates/face.html
{% extends "base.html" %}
    {% load static %}
    {% block customhead %}
    <link rel="stylesheet" type="text/css" href="{% static 'styleProduct.css' %}">
    {% endblock customhead %}
    {% block content %}
    <!-- face category -->
    <div id="faceCategory">
      <div class="container">
        <div class="row">
          <div id="category" class="col">
            <h1>Hello, there^^</h1>
              <form method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    {% if gagal %}
                      <p>What's your name?</p>
                      {{faceCategory.nama}}
                      <p>What is your face's skin type?</p>
                      {{faceCategory.faceCategory}}
                      <p style="color: red;"><b>Nama anda belum terdaftar!</b></p>
                    {% else %}
                      <p>What's your name?</p>
                      {{faceCategory.nama}}
                      <p>What is your face's skin type?</p>
                      {{faceCategory.faceCategory}}
                    {% endif %}
                  </div>
                  <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
            <div class="col">
            </div>
        </div>
      </div>
  </div>
    {% endblock content %}

products/templates/skin.html
{% extends "base.html" %}
    {% load static %}
    {% block customhead %}
    <link rel="stylesheet" type="text/css" href="{% static 'styleProduct.css' %}">
    {% endblock customhead %}
    {% block content %}
    <!-- skin category -->
    <div id="skinCategory">
      <div class="container">
        <div class="row">
          <div id="category" class="col">
            <h1>Hello, there^^</h1>
              <form method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    {% if gagal %}
                      <p>What's your name?</p>
                      {{skinCategory.nama}}
                      <p>What is your skin type?</p>
                      {{skinCategory.skinCategory}}
                      <p style="color: red;"><b>Nama anda belum terdaftar!</b></p>
                    {% else %}
                      <p>What's your name?</p>
                      {{skinCategory.nama}}
                      <p>What is your skin type?</p>
                      {{skinCategory.skinCategory}}
                    {% endif %}
                  </div>
                  <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
            <div class="col">
            </div>
        </div>
      </div>
  </div>
    {% endblock content %}