advice/urls.py
from django.urls import path
from . import views
from .views import terima_advice

app_name = 'advice'

urlpatterns = [
    path('', views.index_advice, name='index'),
    path('send/', terima_advice, name="ya"),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('advice/', include('advice.urls')),
    path('products/', include('products.urls')),
    path('review/', include('reviewPage.urls')),
]

advice/models.py
from django.db import models

# Create your models here.
class AdviceModel(models.Model):
    namaAdvice = models.CharField(max_length=200)
    isiAdvice = models.CharField(max_length=2000)

    def __str__(self):
        return self.isiAdvice

advice/forms.py
from django import forms

class AdviceForm(forms.Form):
    # Nama
    namaAdvice = forms.CharField(label='Nama', max_length=200)

    # Isi advice
    isiAdvice = forms.CharField(label='Advice', widget=forms.Textarea, max_length=2000)

advice/views.py
from django.shortcuts import render
from .forms import AdviceForm
from .models import AdviceModel

# Create your views here.
def index_advice(request):
    advice_form = AdviceForm()
    argument = {
        'advice_form' : advice_form
    }
    return render(request, 'advice/index.html', argument)

def terima_advice(request):
    advice_form = AdviceForm(request.POST)
    isianNama = request.POST['namaAdvice']
    isianAdvice = request.POST['isiAdvice']

    temp = AdviceModel(
        namaAdvice = isianNama,
        isiAdvice = isianAdvice,
    )

    temp.save()

    argument = {
        'advice_form' : advice_form
    }

    return render(request, 'advice/index.html', argument)
    

advice/templates/advice/index.html
{% extends "base.html" %}
{% load static %}

{% block customhead %}
    <link rel="stylesheet" type="text/css" href="{% static 'styleAdvice.css' %}">
{% endblock customhead %}

{% block content %}
    <!-- header advice -->
    <header class="container pb-5">
        <h1 class="display-3 text-light heading">We need your<br>advice</h1>
        <br>
        <section class="jumbotron">
            <div class="adviceJumbotron">
                <form method="POST" action="{% url 'advice:ya' %}">
                    {% csrf_token %}
                    <table>
                        {{advice_form.as_table}}
                    </table>
                    <div>
                        <input type="submit" value="Send your advice" name="tombol">
                    </div>
                </form>
            </div>
        </section>


    </header>
{% endblock content %}