advice/urls.py
from django.urls import path
from . import views
from .views import terima_advice

app_name = 'advice'

urlpatterns = [
    path('', views.index_advice, name='index'),
    path('send/', terima_advice, name="ya"),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('summary/', views.summary, name = 'summary'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('hair/', views.hair, name='hair'),
    path('dandruff/', views.dandruff, name='dandruff'),
    path('hairLoss/', views.hairLoss, name='hairLoss'),
    path('dryHair/', views.dryHair, name='dryHair'),
    path('face/', views.face, name='face'),
    path('jerawat/', views.jerawat, name='jerawat'),
    path('berminyak/', views.berminyak, name='berminyak'),
    path('keringFace/', views.keringFace, name='keringFace'),
    path('normalFace/', views.normalFace, name='normalFace'),
    path('skin/', views.skin, name='skin'),
    path('normalSkin/', views.normalSkin, name='normalSkin'),
    path('drySkin/', views.drySkin, name='drySkin'),
    path('sensitifSkin/', views.sensitifSkin, name='sensitifSkin'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('advice/', include('advice.urls')),
    path('products/', include('products.urls')),
    path('review/', include('reviewPage.urls')),
]

homepage/models.py
from django.db import models
from products.models import hairCategory, faceCategory, skinCategory

gender = [
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE'),
]

class Person(models.Model):
    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=6, choices=gender)
    hair = models.ManyToManyField(hairCategory)
    face = models.ManyToManyField(faceCategory)
    skin = models.ManyToManyField(skinCategory)

    def __str__(self):
        return self.name

    def get_hair_values(self):
        hair = ''
        for h in hairCategory.objects.filter(nama = self.name).values_list('hairCategory', flat=True):
            hair = h
        return hair

    def get_skin_values(self):
        skin = ''
        for s in skinCategory.objects.filter(nama = self.name).values_list('skinCategory', flat=True):
            skin = s
        return skin

    def get_face_values(self):
        face = ''
        for f in faceCategory.objects.filter(nama = self.name).values_list('faceCategory', flat=True):
            face = f
        return face
    

    

homepage/forms.py
from django import forms
from .models import Person


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['name','gender']
        widgets = {
            'name' : forms.TextInput(attrs={
					'class': 'form-control'
					}),
            'gender' : forms.Select(attrs={
					'class': 'form-control'
					}),
        }

homepage/views.py
from django.shortcuts import render, redirect
from .forms import PersonForm
from .models import Person

# Create your views here.
def home(request):
    if request.method == "POST":
        form = PersonForm(request.POST)
        if form.is_valid():
            if Person.objects.filter(name = request.POST['name']).exists():
                arguments = {
                    'form' : PersonForm(),
                    'ada' : True,
                    'tidak_valid' : False,
                }
                return render(request, 'home.html', arguments)
            else:
                form.save()
                return redirect('products:hair')
        arguments = {
            'form' : PersonForm(),
            'ada' : False,
            'tidak_valid' : True,
        }
        return render(request, 'home.html', arguments)
    
    form = PersonForm()

    arguments = {
        'form': form,
        'ada' : False,
        'tidak_valid' : False,
    }

    return render(request, 'home.html', arguments)


def summary(request):
    person = Person.objects.all()
    arguments = {
        'person' : person,
    }
    return render(request, 'summary.html', arguments)

homepage/templates/base.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <title>BODYOLOGY</title>
        <meta charset="UTF-8">
        <meta name=”viewport” content=”width=device-width, initial-scale=1″>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
        {% block customhead %}
        {% endblock customhead %}
        
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'homepage:home' %}">Bodyology</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0"></ul>
              <form class="form-inline my-2 my-lg-0">
                    <a class="nav-link" href="{% url 'homepage:home' %}">HOME</a>
                    <a class="nav-link" href="{% url 'products:hair' %}">HAIR</a>
                    <a class="nav-link" href="{% url 'products:face' %}">FACE</a>
                    <a class="nav-link" href="{% url 'products:skin' %}">SKIN</a>
                    <a class="nav-link" href="{% url 'homepage:summary' %}">SUMMARY</a>
                    <a class="nav-link" href="{% url 'advice:index' %}">ADVICE</a>
              </form>
            </div>
          </nav>
          {% block content %}
          {% endblock content %}
        <!-- JavaScript -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/esm/popper-utils.js"></script>
        <script src="{% static 'bootstrap.bundle.min.js' %}"></script> 
    </body>
</html>

homepage/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block customhead %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock customhead %}

{% block content %}

<div id='homepage'>
    <div class="container">
        <div class="box">
            <div class="row">
              <h1 class="hello col-md-12 col-sm-12">Hello,</h1>
            </div>
            <div class="row">
                <h1 class="welcome col-md-12 col-sm-12">Welcome to Bodyology</h1>
            </div>
            <div class="row">
              <h3 class="brief col-md-12 col-sm-12">Let me help you to find the best products for you</h3>
            </div>
        </div>
    </div>
</div>

<div id='homepage2'>
  <div class='container'>
    <div class="row">
        <div class="col-md-6 col-sm-12">
          <div class="box-2">
              <div class="row">
                  <h2 class="title-1">Personalized product recommendation that match your needs</h2>
                </div>
                <div class="row">
                  <h6 class="title-2">Join today and get the best care for your body</h6>
                </div>
          </div>
        </div>

        <div class="form col-md-6 col-sm-12">
            <form method="POST" action="{% url 'homepage:home' %}" class="form-group">
                {% csrf_token %}
                {% if ada %}
                    <p class="row warning">This name is already taken</p>
                    <div class="pad row">
                        <h6 class="question">What is your name?</h6>
                    </div>
                    <div class="form-pad row">
                        {{ form.name }}
                    </div>
                    <div class="pad question row">
                        <h6 class="question">What is your gender?</h6>
                    </div>
                    <div class="form-pad row">
                        {{ form.gender }}
                    </div>
                    
                    <div class=" button-submit row">
                        <input type="submit" value="Submit" class="btn btn-primary" >
                    </div>
                {% elif tidak_valid %}
                    <p class="row warning">Your input is not valid</p>
                    <div class="pad row">
                        <h6 class="question">What is your name?</h6>
                    </div>
                    <div class="form-pad row">
                        {{ form.name }}
                    </div>
                    <div class="pad question row">
                        <h6 class="question">What is your gender?</h6>
                    </div>
                    <div class="form-pad row">
                        {{ form.gender }}
                    </div>
                    
                    <div class=" button-submit row">
                        <input type="submit" value="Submit" class="btn btn-primary" >
                    </div>
                {% else %}
                    <div class="pad row">
                        <h6 class="question">What is your name?</h6>
                    </div>
                    <div class="form-pad row">
                        {{ form.name }}
                    </div>
                    <div class="pad question row">
                        <h6 class="question">What is your gender?</h6>
                    </div>
                    <div class="form-pad row">
                        {{ form.gender }}
                    </div>
                    
                    <div class=" button-submit row">
                        <input type="submit" value="Submit" class="btn btn-primary" >
                    </div>
                {% endif %}
            </form>
        </div> 
  </div>

</div>

{% endblock content %}

homepage/templates/summary.html
{% extends 'base.html' %}
{% load static %}

{% block customhead %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock customhead %}

{% block content %}
<div class="container">
    <div id="summary">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <h1 id="summary-title">Summary</h1>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <table class="table table-bordered">
                    <thead>
                      <tr class="table-head">
                            <th>Name</th>
                            <th>Gender</th>
                            <th>Hair</th>
                            <th>Face</th>
                            <th>Skin</th>
                      </tr>
                    </thead>
                            
                    <tbody>
                            {% for p in person %}
                                <tr>
                                    <td>{{ p.name }}</td>
                                    <td>{{ p.gender }}</td>
                                    <td>{{ p.get_hair_values }}</td>
                                    <td>{{ p.get_face_values }}</td>
                                    <td>{{ p.get_skin_values }}</td>
                                </tr>
                            {% endfor %}
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
</div>


{% endblock content %}